services:
  broker:
    image: apache/kafka:latest
    hostname: broker
    container_name: broker
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://broker:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:29093
      KAFKA_LISTENERS: PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server broker:29092 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 20s
    extends:
      file: common-config.yml
      service: network-deploy-service

  pessoadb:
    container_name: pessoadb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: rod
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pessoa_service
    extends:
      file: common-config.yml
      service: microservice-postgres-config
    volumes:
      # Monta o arquivo init.sql para inicialização do banco
      - ./db-configs/postgres/init_pessoa.sql:/docker-entrypoint-initdb.d/init_pessoa.sql
      - postgres_pessoa_data:/var/lib/postgresql/data

  produtodb:
    container_name: produtodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: produto
      MONGO_INITDB_ROOT_PASSWORD: produto
      MONGO_INITDB_DATABASE: produtodb
    extends:
      file: common-config.yml
      service: microservice-mongo-config
    volumes:
      - mongo_produto_data:/data/db

  estoquedb:
    container_name: estoquedb
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: estoque
      MONGO_INITDB_ROOT_PASSWORD: estoque
      MONGO_INITDB_DATABASE: estoquedb
    extends:
      file: common-config.yml
      service: microservice-mongo-config
    volumes:
      - mongo_estoque_data:/data/db

  configserver:
    container_name: configserver-rd
    build:
      context: ../../configserver
      dockerfile: Dockerfile
    ports:
      - "8071:8071"
    depends_on:
      broker:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    extends:
      file: common-config.yml
      service: microservice-base-config

  pessoa-service:
    container_name: pessoa-service-rd
    build:
      context: ../../pessoa-service
      dockerfile: Dockerfile
    ports:
      - "8084:8080"
    depends_on:
      configserver:
        condition: service_healthy
      pessoadb:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "pessoa-service"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://pessoadb:5432/pessoa_service"
    extends:
      file: common-config.yml
      service: microservice-base-config

  produto-service:
    container_name: produto-service-rd
    build:
      context: ../../produto-service
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      configserver:
        condition: service_healthy
      produtodb:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "produto-service"
      SPRING_DATA_MONGO_URI: "mongodb://produto:produto@produtodb:27017/produtodb?authSource=admin"
      SPRING_INTEGRACAO_URL: "http://pessoa-service:8084"
    extends:
      file: common-config.yml
      service: microservice-base-config

  estoque-service:
    container_name: estoque-service-rd
    build:
      context: ../../estoque-service
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
    depends_on:
      configserver:
        condition: service_healthy
      estoquedb:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "estoque-service"
      SPRING_DATA_MONGO_URI: "mongodb://estoque:estoque@estoquedb:27017/estoquedb?authSource=admin"
    extends:
      file: common-config.yml
      service: microservice-base-config

  notification-service:
    container_name: notification-service-rd
    build:
      context: ../../notification-service
      dockerfile: Dockerfile
    ports:
      - "8085:8080"
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "notification-service"
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_USERNAME: ${EMAIL_USERNAME}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      TWILIO_ACCOUNTID: ${TWILIO_ACCOUNTID}
      TWILIO_TOKEN: ${TWILIO_TOKEN}
      TWILIO_PHONE: ${TWILIO_PHONE}
    extends:
      file: common-config.yml
      service: microservice-base-config

networks:
  roddev:
      driver: "bridge"

volumes:
  postgres_pessoa_data:
  mongo_produto_data:
  mongo_estoque_data: