services:
  broker:
    image: apache/kafka:latest
    hostname: kafka-broker
    container_name: kafka-broker
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:29093
      KAFKA_LISTENERS: PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    healthcheck:
      test: [ "CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 20s
    extends:
      file: common-config.yml
      service: network-deploy-service

  configserver:
    container_name: configserver-rd
    build:
      context: ../../configserver
      dockerfile: Dockerfile
    ports:
      - "8071:8071"
    depends_on:
      broker:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  pessoa-service:
    container_name: pessoa-service-rd
    build:
      context: ../../pessoa-service
      dockerfile: Dockerfile
    ports:
      - "8084:8080"
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "pessoa-service"
    extends:
      file: common-config.yml
      service: microservice-base-config

  produto-service:
    container_name: produto-service-rd
    build:
      context: ../../produto-service
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "produto-service"
    extends:
      file: common-config.yml
      service: microservice-base-config

  estoque-service:
    container_name: estoque-service-rd
    build:
      context: ../../estoque-service
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "estoque-service"
    extends:
      file: common-config.yml
      service: microservice-base-config

  notification-service:
    container_name: notification-service-rd
    build:
      context: ../../notification-service
      dockerfile: Dockerfile
    ports:
      - "8085:8080"
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "notification-service"
    extends:
      file: common-config.yml
      service: microservice-base-config

networks:
  roddev:
      driver: "bridge"